nome = input('Escreva o nome do aluno: ')
nota1 = float(input('Escreva a primeira nota do aluno: '))
nota2 = float(input('Escreva a segunda nota do aluno: '))
media = (nota1 + nota2) / 2
print('-' * 40)
print('Notas do aluno: ', nome)
print('-' * 40)
print('Nota 1 = ', nota1)
print('Nota 2 = ', nota2)
print('Média do aluno: ', media)