nome = str(input('Digite o seu nome completo: ')).title().strip()
print('Muito prazer em te conhecer, {}!!'.format(nome))
separa = nome.split()
print('Seu primeiro nome é: {}'.format(separa[0]))
print('Seu último nome é: {}'.format(separa[len(separa)-1]))
