valor = input('Digite algo: ')
print('Só tem espaços? ', valor.isspace())
print('É um número? ', valor.isnumeric())
print('É alfabético? ', valor.isalpha())
print('É alfanumérico? ', valor.isalnum())
print('Está em caixa ALTA? ', valor.isupper())
print('Está em caixa baixa? ', valor.islower())
#print('Está capitalizada? ', valor.is())
print('O valor pode ser impresso? ', valor.isprintable())